name: Eskimska vas
favicon: null
layout_spectrum: 0.8494172196369618
typography_spectrum: 0.4971040200907737
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.7603148408234119
  lightness: 0.09470254182815552
  saturation: 0.5928232942242175
  rhythmicContrast: 0.6118946955539286
purpose: []
